name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          pkgs: simg2img
        - os: ubuntu-22.04
          pkgs: simg2img
          fake: sudo rm /usr/include/linux/fiemap.h /usr/include/linux/fs.h
          env: ac_cv_func_fallocate=no
        - os: ubuntu-24.04
          pkgs: android-sdk-libsparse-utils erofs-utils
        - os: ubuntu-26.04
          pkgs: android-sdk-libsparse-utils erofs-utils

    steps:
    - name: Inspect environment
      run: |
        whoami
        lsb_release -a
        gcc --version

    - uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install arm-trusted-firmware-tools btrfs-progs device-tree-compiler dosfstools f2fs-tools fakeroot genext2fs genisoimage libconfuse-dev mdadm mtd-utils mtools qemu-utils qemu-utils rauc squashfs-tools u-boot-tools ${{ matrix.pkgs }}
        ${{ matrix.fake }}

    - name: Build & Test (with ${{ matrix.options }})
      run: |
        ./autogen.sh
        ./configure
        ${{ matrix.env }} M_COLOR_TESTS=always make distcheck

    - name: Dump test log
      if: ${{ failure() }}
      run: |
        find -name test-suite.log -print0 | xargs -0 cat

