name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          pkgs: device-tree-compiler rauc simg2img u-boot-tools f2fs-tools arm-trusted-firmware-tools btrfs-tools
        - os: ubuntu-22.04
          pkgs: device-tree-compiler rauc simg2img u-boot-tools f2fs-tools arm-trusted-firmware-tools btrfs-tools 
          fake: sudo rm /usr/include/linux/fiemap.h /usr/include/linux/fs.h
          env: ac_cv_func_fallocate=no
        - os: ubuntu-20.04
          pkgs: device-tree-compiler rauc simg2img u-boot-tools f2fs-tools btrfs-tools 

    steps:
    - name: Inspect environment
      run: |
        whoami
        lsb_release -a
        gcc --version

    - uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install dosfstools fakeroot genext2fs genisoimage libconfuse-dev mtd-utils mtools qemu-utils qemu-utils squashfs-tools ${{ matrix.pkgs }}
        ${{ matrix.fake }}

    - name: Build & Test (with ${{ matrix.options }})
      run: |
        ./autogen.sh
        ./configure
        ${{ matrix.env }} M_COLOR_TESTS=always make distcheck

    - name: Dump test log
      if: ${{ failure() }}
      run: |
        find -name test-suite.log -print0 | xargs -0 cat

